version: 2.1
orbs:
  node: circleci/node@5.1.0
  aws-ecr: circleci/aws-ecr@8.2.1
jobs:
  build-backend:
    executor: node/default
    working_directory: ~/ce-todo-list-project
    docker:
      - image: cimg/node:20.2.0
        environment:
            DATABASE_HOST: postgres-db
    steps:
      - checkout
      - node/install:
          node-version: latest
      - node/install-packages:
          app-dir: ~/ce-todo-list-project/backend-api
      - run:
          name: Start
          command: nohup npm run start &
  build-frontend:
    executor: node/default
    working_directory: ~/ce-todo-list-project
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - node/install:
          node-version: latest
      - node/install-packages:
          app-dir: ~/ce-todo-list-project/todo-frontend
      - run:
          name: Start
          command: nohup nginx -g daemon off &
  build-database:
    working_directory: ~/ce-todo-list-project
    docker:
      - image: postgres:9.4.1
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: list_items
    steps:
      - checkout
      - run:
          name: Start
          command: ls
  build-image-and-push-backend:
    working_directory: ~/ce-todo-list-project/backend-api
    docker:
      - image: cimg/aws:2023.05
    steps:
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          repo: nc-backend
          path: ./
          build-path: "./"
          tag: ${CIRCLE_BUILD_NUM}
          public-registry-alias: f7n0z5e3
          public-registry: true
          create-repo: true
  build-image-and-push-frontend:
    working_directory: ~/ce-todo-list-project/todo-frontend
    docker:
      - image: cimg/aws:2023.05
    steps:
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          repo: nc-frontend
          path: ./
          build-path: "./"
          tag: ${CIRCLE_BUILD_NUM}
          public-registry-alias: f7n0z5e3
          public-registry: true
          create-repo: true
  build-image-and-push-database:
    working_directory: ~/ce-todo-list-project/database
    docker:
      - image: cimg/aws:2023.05
    steps:
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          repo: nc-database
          path: ./
          build-path: "./"
          tag: ${CIRCLE_BUILD_NUM}
          public-registry-alias: f7n0z5e3
          public-registry: true
          create-repo: true
workflows:
  demo-app-pipeline:
    jobs:
      - build-backend
      - build-frontend
      - build-database
      - build-image-and-push-backend:
          requires:
            - build-backend
      - build-image-and-push-frontend:
          requires:
            - build-frontend
      - build-image-and-push-database:
          requires:
            - build-database
