version: 2.1
orbs:
  node: circleci/node@5.1.0
  aws-ecr: circleci/aws-ecr@8.2.1
jobs:
  build-backend:
    executor: node/default
    working_directory: ~/backend-api
    docker:
      - image: cimg/node:20.2.0
        environment:
            DATABASE_HOST: postgres-db
    steps:
      - checkout
      - node/install:
          node-version: latest
      - node/install-packages
      - run:
          name: Start
          command: nohup npm run start &
          working_directory: ~/backend-api
  build-frontend:
    executor: node/default
    working_directory: ~/todo-frontend
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - node/install:
          node-version: latest
      - node/install-packages
      - run:
          name: Start
          command: nohup nginx -g daemon off &
          working_directory: ~/todo-frontend
  build-database:
    working_directory: ~/database
    docker:
      - image: postgres:9.4.1
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: list_items
    steps:
      - checkout
      - node/install:
          node-version: latest
      - node/install-packages
      - run:
          name: Start
          command: nohup nginx -g daemon off &
          working_directory: ~/database
  build-image-and-push-backend:
    working_directory: ~/backend-api
    docker:
      - image: cimg/aws:2023.05
    steps:
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          repo: nc-backend
          path: ./