# Dont forget those env vars (DATABASE_HOST) so the backend knows where the database lives
# You can use internal DNS for pointing the backend API at the database
# For example if you setup a service for the database called database-service then the internal 
# host name is database-service.default.svc.cluster.local